---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---

library setup
```{r message=FALSE}
packages.used <- c("EBImage","R.matlab","readxl","dplyr","ggplot2","caret",
                   "glmnet","WeightedROC","gbm","xgboost", "AUC")

packages.needed <- setdiff(packages.used, intersect(installed.packages()[,1], packages.used))

if(length(packages.needed) > 0){
   install.packages(packages.needed, dependencies = TRUE)
}

library(R.matlab)
library(readxl)
library(dplyr)
library(EBImage)
library(ggplot2)
library(caret)
library(glmnet)
library(WeightedROC)
library(gbm)
library(xgboost)
library(AUC)
```


set dir
```{r}
#change to testset folder name on presentation day
#test_dir <- "../data/test_set/" 
test_dir <- "../data/train-set/" 

test_image_dir <- paste(test_dir, "images/", sep="")
test_pt_dir <- paste(test_dir,  "points/", sep="")
test_label_path <- paste(test_dir, "label_prediction.csv", sep="") 
```

pre-operation: read fiducial points
```{r}
n_files <- length(list.files(test_image_dir))

#readMat.matrix <- function(index){
#  return(round(readMat(paste0(test_pt_dir, sprintf("%04d", index), ".mat"))[[1]],0))
#}
#fiducial_pt_list <- lapply(1:n_files, readMat.matrix)

load(file="../output/fiducial_pt_list.RData")

features
Index <- c(1:n_files)
info = data.frame(Index)
info$label = rep(-1, n_files) 
test_idx <- c(1:n_files)

source("../lib/feature.R")
tm_feature_test <- NA
tm_feature_test <- system.time(dat_test <- feature(fiducial_pt_list, test_idx))
feature_test <- as.matrix(dat_test[, -6007])
```



test for baseline model
```{r}
load(file="../output/fit_train_gbm.RData")
source("../lib/test_gbm.R")

prob_pred_gbm <- test(fit_train_gbm, feature_test, pred.type = 'response')
label_pred_gbm <- ifelse(prob_pred_xgboost >= 0.5, 1, 0)
```



test for xgboost model

```{r}
load(file="../output/xgb_fit_train.RData") 
source("../lib/test_XGBoost.R")
prob_pred_xgboost <- xgbtest(fit_train, feature_test)
label_pred_xgboost <- ifelse(prob_pred_xgboost >= 0.5, 1, 0)
```

write file

```{r}
Index <- c(1:n_files)
Baseline <- label_pred_gbm
Advanced <- label_pred_xgboost

label_predicted <- cbind(Index, Baseline, Advanced)

write.csv(label_predicted,'../output/label_prediction.csv', row.names = FALSE)
```

