---
title: "R Notebook"
output: html_notebook
---

library setup
```{r message=FALSE}
if(!require("EBImage")){
  install.packages("BiocManager")
  BiocManager::install("EBImage")
}
if(!require("R.matlab")){
  install.packages("R.matlab")
}
if(!require("readxl")){
  install.packages("readxl")
}

if(!require("dplyr")){
  install.packages("dplyr")
}
if(!require("readxl")){
  install.packages("readxl")
}

if(!require("ggplot2")){
  install.packages("ggplot2")
}

if(!require("caret")){
  install.packages("caret")
}

if(!require("glmnet")){
  install.packages("glmnet")
}

if(!require("WeightedROC")){
  install.packages("WeightedROC")
}

library(R.matlab)
library(readxl)
library(dplyr)
library(EBImage)
library(ggplot2)
library(caret)
library(glmnet)
library(WeightedROC)

if(!require("xgboost")){
  install.packages("xgboost")
}
library(xgboost)
```


set dir
```{r}
test_dir <- "../data/test_set_predict/" 

test_image_dir <- paste(test_dir, "images/", sep="")
test_pt_dir <- paste(test_dir,  "points/", sep="")
test_label_path <- paste(test_dir, "label_prediction.csv", sep="") 
```

pre-operation
```{r}
n_files <- length(list.files(test_image_dir))
#points
readMat.matrix <- function(index){
  return(round(readMat(paste0(test_pt_dir, sprintf("%04d", index), ".mat"))[[1]],0))
}
fiducial_pt_list <- lapply(1:n_files, readMat.matrix)
#features
Index <- c(1:n_files)
info = data.frame(Index)
info$label = rep(-1, n_files) 
test_idx <- c(1:n_files)

source("../lib/feature.R")
tm_feature_test <- NA
tm_feature_test <- system.time(dat_test <- feature(fiducial_pt_list, test_idx))
feature_test <- as.matrix(dat_test[, -6007])
```

test 
```{r}
#load(file="../output/***.RData") 
#source("../lib/***.R") 
#prob_pred_gbm <- ***
#label_pred_gbm <- ***

load(file="../output/xgb_fit_train.RData") 
source("../lib/test_XGBoost.R")
prob_pred_xgboost <- xgbtest(xgb_fit_train, feature_test)
label_pred_xgboost <- ifelse(prob_pred_xgboost >= 0.5, 1, 0)
```

write file
```{r}
Index <- c(1:n_files)
Baseline <- label_pred_gbm
Advanced <- label_pred_xgboost

label_predicted <- cbind(Index, Baseline, Advanced)

write.csv(label_predicted,'../output/label_prediction.csv', row.names = FALSE)
```

